### ISSUE TITLE
Q1: How many people recorded in this dataset are alive, and how many are dead?

### ISSUE THREAD

**Issue by jonjoncardoso** [lse-ds105/w08-w09-imdb-data#2]
Help!

Remember to wrap your code with **beautiful** syntax highlight:

\`\`\`python
.... your code here..
\`\`\`

**Comment by KristinaD1910** [comment]
```python
num_dead = len(list(df_name_basics[df_name_basics["deathYear"] == "\\N"]))
num_dead
```

**Comment by jonjoncardoso** [comment]
> ```python
> num_dead = len(list(df_name_basics[df_name_basics["deathYear"] == "\\N"]))
> num_dead
> ```

But we have already gotten rid of the `\\N`!

**Comment by KristinaD1910** [comment]
```python
num_dead = len(list(df_name_basics[df_name_basics["deathYear"] == None]))
num_dead
```

**Comment by ruikai30** [comment]
```python
df_name_basics['deathYear'].isna().sum()
```

**Comment by jonjoncardoso** [comment]
Here's a final version:

```python
df_name_basics['is_alive'] = df_name_basics['deathYear'].isna()
df_name_basics['is_alive'].value_counts()
```

And in case you enjoy practising some f-strings:

```python
print(f"Answer: {df_name_basics['is_alive'].value_counts()[True]} people are presumed alive")
print(f"Answer: {df_name_basics['is_alive'].value_counts()[False]} people are dead")
```

**Comment by jonjoncardoso** [comment]
Closing this issue now that I have replicated the code above to the notebook in this commit: https://github.com/lse-ds105/w08-w09-imdb-data/commit/3d2e6e0677dc5ebd19950f2c7742fa62c52ea85d
